### ISSUE TITLE
getDisplayeDate method

### ISSUE THREAD

**Issue by amirMohammadi0007** [alibehzadian/PersianDatePicker#10]
سلام
متدهای تعریف شده برای گرفتن تاریخ انتخاب شده به درستی کار نمیکند.لطفا در صورت اشتباه از طرف بنده نحوه استفاده درست از این متد را توضیح دهید و یا در صورت اشتباه بودن متد و عدم جوابگویی آن را اصلاح نمایید.با تشکر

**Comment by alibehzadian** [comment]
«به درستی کار نمیکند» یعنی چه؟ Exception دارد؟ تاریخ درستی نشان نمی‌دهد؟
