### ISSUE TITLE
Problem in import

### ISSUE THREAD

**Issue by asenaismaeili** [alibehzadian/PersianDatePicker#11]
با سلام
من پروژه مورد نظر رو دانلود و به پروژه خودم اضافه کردم ولی متاسفانه موقع سینک کردن گریدل Error:Configuration with name 'default' not found.
این خطا رو می دهد
از روش دوم هم استقاده کردم و تمامی کدها رو به پروژه اضافه کردم ولی این سری با خود کلاس هایی که شما نوشته بودید مشکل داره
می تونید راهنمایی کنید؟
ممنون می شم

**Comment by alibehzadian** [comment]
مشکل از اتصال اینترنتی شما است
