### ISSUE TITLE
Problem with timezone

### ISSUE THREAD

**Issue by Omid-naji** [alibehzadian/PersianDatePicker#18]
I went the following methods:

pCal.setTimeZone (TimeZone.getTimeZone ( "Iran"));
&
pCal.setTimeZone (TimeZone.getTimeZone ( "Asia / Tehran"));
&
pCal.setTimeZone (TimeZone.getTimeZone ( "GMT + 03: 30"));

**Comment by alibehzadian** [comment]
I have totally changed Calendar library and problem is solved. I need more time to test the library and publish it again.

**Comment by Omid-naji** [comment]
Thank you for your attention

**Comment by mohsen202** [comment]
سپاس
