### ISSUE TITLE
how to convert to miladi date?

### ISSUE THREAD

**Issue by moslem-pc** [alibehzadian/PersianDatePicker#4]
hi mr behzadian
very good library 2 use!
but i didnt find any functions to return miladi date, guid me if there is any way!
TnX ;)

**Comment by alibehzadian** [comment]
PersianCalendar has some methods to convert persian date to gregorian date.

**Comment by moslem-pc** [comment]
can u pls tell me what the methods are? i couldn't find any!
tnX

**Comment by alibehzadian** [comment]
GregorianCalendar gregorianCalendar = new GregorianCalendar();
gregorianCalendar.setTime(persianCalendar.getTime());

You can find more here (In persian): http://smartlab.ir/%D8%AA%D8%A7%D8%B1%DB%8C%D8%AE-%D9%88-%D8%AA%D9%82%D9%88%DB%8C%D9%85-%D9%87%D8%AC%D8%B1%DB%8C-%D8%B4%D9%85%D8%B3%DB%8C-%D8%AF%D8%B1-%D8%AC%D8%A7%D9%88%D8%A7/
