### ISSUE TITLE
problem with getDisplayPersianDate()

### ISSUE THREAD

**Issue by mghaffari** [alibehzadian/PersianDatePicker#5]
The output of the function "getDisplayPersianDate()" is as written below. I would be thankful if you modify it:

at.andreasrohner.spartantimelapserec.persindatepicker.util.PersianCalendar[time=1312653074599,areFieldsSet=true,lenient=true,zone=GMT,firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2011,MONTH=7,WEEK_OF_YEAR=32,WEEK_OF_MONTH=1,DAY_OF_MONTH=6,DAY_OF_YEAR=218,DAY_OF_WEEK=7,DAY_OF_WEEK_IN_MONTH=1,AM_PM=1,HOUR=5,HOUR_OF_DAY=17,MINUTE=51,SECOND=14,MILLISECOND=599,ZONE_OFFSET=0,DST_OFFSET=0,PersianDate=1390/05/15]

**Comment by alibehzadian** [comment]
The "getDisplayPersianDate()" method returns a PersianCalendar object. You can call "getPersianShortDate()" or "getPersianLongDate()" on this object to get the result you want.
