### ISSUE TITLE
نمایش تاریخ جاری سیستم در هر صورت

### ISSUE THREAD

**Issue by AtefehSoveyzi** [alibehzadian/PersianDatePicker#8]
مشکلم اینجاست که همواره مقدار تاریخ جاری رو بهم برمیگردونه ! ینی هر چقدر من عوض میکنم هیچ اتفاقی نمیوفته.
اما متد شما میگه getDisplayPersianDate !!
ینی تاریخی که داری نمایش میدی رو برگردون. !!! نه تاریخ جاری رو !!
ممنون میشم راهنمایی کنید.

**Comment by alibehzadian** [comment]
getDisplayPersianDate() method returns a PersianCalendar instance with selected date. You can extract date from that instance. For example:
PersianCalendar pCal = picker.getDisplayPersianDate();
int year = pCal.getPersianYear();
int month = pCal.getPersianMonth();
int day = pCal.getPersianDay();
